["Windows-10-Dark.Denis-Velikanov"]
    type = "archive"
    url = "https://github.com/0x0003/ImageGlass-Themes/releases/download/8.3/Windows-10-Dark.Denis-Velikanov.igtheme"
    format = "zip"
    stripComponents = 1
