music_directory    "/mnt/media/music"
playlist_directory "~/.local/share/mpd/playlists"
db_file            "~/.local/share/mpd/mpd.db"
log_file           "~/.local/share/mpd/mpd.log"
state_file         "~/.local/share/mpd/state"
sticker_file       "~/.local/share/mpd/sticker.sqlite"

restore_paused "yes"

audio_output {
  name "Default Output"
  type "pipewire"
}

