[general]
live_config_reload = false

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
# ref_test = false
render_timer = false

[font]
# size = 14.0
size = 16.5

[font.normal]
family = "IosevkaCustom Nerd Font Mono"
# family =  "JetBrains Mono"
style = "Regular"

[font.bold]
family = "IosevkaCustom Nerd Font Mono"
# family =  "JetBrains Mono"
style = "Medium"

[font.italic]
family = "IosevkaCustom Nerd Font Mono"
# family =  "JetBrains Mono"
style = "Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "SearchConfirm"
key = "Return"
mode = "Search|Vi"

[[keyboard.bindings]]
action = "SearchCancel"
key = "Escape"
mode = "Search"

[[keyboard.bindings]]
action = "SearchCancel"
key = "C"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchClear"
key = "U"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchDeleteWord"
key = "W"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchHistoryPrevious"
key = "P"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchHistoryNext"
key = "N"
mode = "Search"
mods = "Control"

[[keyboard.bindings]]
action = "SearchHistoryPrevious"
key = "Up"
mode = "Search"

[[keyboard.bindings]]
action = "SearchHistoryNext"
key = "Down"
mode = "Search"

[[keyboard.bindings]]
action = "SearchFocusNext"
key = "Return"
mode = "Search|~Vi"

[[keyboard.bindings]]
action = "SearchFocusPrevious"
key = "Return"
mode = "Search|~Vi"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u0000"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

# tmux keybinds; C-s as prefix
# --------------------------------------------------
# pane left
[[keyboard.bindings]]
chars = "\u0013\u0068"
key = "H"
mods = "Alt"
# pane down
[[keyboard.bindings]]
chars = "\u0013\u006a"
key = "J"
mods = "Alt"
# pane up
[[keyboard.bindings]]
chars = "\u0013\u006b"
key = "K"
mods = "Alt"
# pane right
[[keyboard.bindings]]
chars = "\u0013\u006c"
key = "L"
mods = "Alt"
# kill active pane
[[keyboard.bindings]]
chars = "\u0013\u0078"
key = "W"
mods = "Alt"
# zoom in on  active pane
[[keyboard.bindings]]
chars = "\u0013\u007a"
key = "Z"
mods = "Alt"

# prev window
[[keyboard.bindings]]
chars = "\u0013\u0070"
key = "p"
mods = "Alt"
# next window
[[keyboard.bindings]]
chars = "\u0013\u006e"
key = "n"
mods = "Alt"

# jump to window by number
[[keyboard.bindings]]
chars = "\u0013\u0031"
key = "1"
mods = "Alt"
[[keyboard.bindings]]
chars = "\u0013\u0032"
key = "2"
mods = "Alt"
[[keyboard.bindings]]
chars = "\u0013\u0033"
key = "3"
mods = "Alt"
[[keyboard.bindings]]
chars = "\u0013\u0034"
key = "4"
mods = "Alt"
[[keyboard.bindings]]
chars = "\u0013\u0035"
key = "5"
mods = "Alt"
[[keyboard.bindings]]
chars = "\u0013\u0036"
key = "6"
mods = "Alt"
[[keyboard.bindings]]
chars = "\u0013\u0037"
key = "7"
mods = "Alt"
[[keyboard.bindings]]
chars = "\u0013\u0038"
key = "8"
mods = "Alt"
[[keyboard.bindings]]
chars = "\u0013\u0039"
key = "9"
mods = "Alt"
[[keyboard.bindings]]
chars = "\u0013\u0030"
key = "0"
mods = "Alt"

# break pane (move to new window)
[[keyboard.bindings]]
chars = "\u0013\u0075"
key = "U"
mods = "Alt"
# bring pane from named window
[[keyboard.bindings]]
chars = "\u0013\u0079"
key = "Y"
mods = "Alt"
# send pane to named window
[[keyboard.bindings]]
chars = "\u0013\u0069"
key = "I"
mods = "Alt"

# new window
[[keyboard.bindings]]
chars = "\u0013\u0063"
key = "T"
mods = "Alt"

# horizontal split
[[keyboard.bindings]]
chars = "\u0013\u0073"
key = "S"
mods = "Alt"
# vertical split
[[keyboard.bindings]]
chars = "\u0013\u0076"
key = "V"
mods = "Alt"

# session switcher
[[keyboard.bindings]]
chars = "\u0013\u006f"
key = "o"
mods = "Alt"
# attach to last session
[[keyboard.bindings]]
chars = "\u0013\u004c"
key = "Backspace"
mods = "Alt"
# prev session
[[keyboard.bindings]]
chars = "\u0013\u0028"
key = "["
mods = "Alt"
# next session
[[keyboard.bindings]]
chars = "\u0013\u0029"
key = "]"
mods = "Alt"
# detach
[[keyboard.bindings]]
chars = "\u0013\u0064"
key = "D"
mods = "Alt"

# tile main-horizontal
[[keyboard.bindings]]
chars = "\u0013\u006d"
key = "M"
mods = "Alt"
# tile main-vertical
[[keyboard.bindings]]
chars = "\u0013\u004d"
key = "M"
mods = "Alt|Shift"

# copy mode
[[keyboard.bindings]]
chars = "\u0013\u0071"
key = "Q"
mods = "Alt"

# resize left
[[keyboard.bindings]]
chars = "\u0013\u001b\u005b\u0044"
key = "Left"
mods = "Alt"
# resize down
[[keyboard.bindings]]
chars = "\u0013\u001b\u005b\u0042"
key = "Down"
mods = "Alt"
# resize up
[[keyboard.bindings]]
chars = "\u0013\u001b\u005b\u0041"
key = "Up"
mods = "Alt"
# resize right
[[keyboard.bindings]]
chars = "\u0013\u001b\u005b\u0043"
key = "Right"
mods = "Alt"
# --------------------------------------------------

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 5000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`| = \"' ()[]{}<>"

[window]
decorations = "none"
dynamic_padding = false
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 15
y = 15

[colors]
draw_bold_text_with_bright_colors = true

# paradise-ed
# --------------------------------------------------
[colors.primary]
background = "#121212"
foreground = "#C5C8C6"

[colors.cursor]
cursor = "#C5C8C6"
# cursor = "#c29448"
text = "#000000"

[colors.normal]
black = "#5a5b5c"
blue = "#8da3b9"
cyan = "#8aa6a2"
green = "#8c997d"
magenta = "#a988b0"
red = "#b66467"
white = "#e8e3e3"
yellow = "#d9bc8c"

[colors.bright]
black = "#3d3e3d"
blue = "#5d7a97"
cyan = "#62817d"
green = "#69735c"
magenta = "#845d8c"
red = "#8f4346"
white = "#8e8e8e"
yellow = "#c29448"

[colors.search.focused_match]
background = "#8f4346"
foreground = "#3d3e3d"

[colors.search.matches]
background = "#8c997d"
foreground = "#3d3e3d"
# --------------------------------------------------

# # gruvbox material dark
# # --------------------------------------------------
# [colors.primary]
# background = "#1d2021" # hard contrast
# # background = "#282828" # medium contrast
# # background = "#32302f" # soft contrast
# foreground = "#d4be98"
#
# [colors.cursor]
# cursor = "#C5C8C6"
# text =   "#000000"
#
# [colors.normal]
# # black =   "#45403d"
# black =   "#5a524c"
# red =     "#ea6962"
# green =   "#a9b665"
# yellow =  "#d8a657"
# blue =    "#7daea3"
# magenta = "#d3869b"
# cyan =    "#89b482"
# white =   "#d4be98"
#
# [colors.bright]
# # black =   "#45403d"
# black =   "#928374"
# red =     "#ef938e"
# green =   "#bbc585"
# yellow =  "#e1bb7e"
# blue =    "#9dc2ba"
# magenta = "#e1acbb"
# cyan =    "#a7c7a2"
# white =   "#e2d3ba"
# # --------------------------------------------------

# # gruvbox light
# # --------------------------------------------------
# [colors.primary]
# # hard contrast
# # background = "#f9f5d7" # hard contrast
# # background = "#fbf1c7" # medium contrast
# background = "#F2E5BC" # soft contrast
# foreground = "#3C3836"
#
# [colors.cursor]
# text =    "#000000"
# cursor =  "#C5C8C6"
#
# [colors.normal]
# # black = "#FBF1C7"
# black = "#928374"
# red = "#CC241D"
# green = "#98971A"
# yellow = "#D79921"
# blue = "#458588"
# magenta = "#B16286"
# cyan = "#689D6A"
# white = "#7C6F64"
#
# [colors.bright]
# black = "#928374"
# red = "#9D0006"
# green = "#79740E"
# yellow = "#B57614"
# blue = "#076678"
# magenta = "#8F3F71"
# cyan = "#427B58"
# white = "#3C3836"
# # --------------------------------------------------

# # kanagawa wave
# # --------------------------------------------------
# [colors.primary]
# background = '#1f1f28'
# # background = '#181820'
# foreground = '#dcd7ba'
#
# [colors.cursor]
# cursor = "#C5C8C6"
# text = "#000000"
#
# [colors.normal]
# # black   = '#090618'
# black   = '#525149'
# red     = '#c34043'
# green   = '#76946a'
# yellow  = '#c0a36e'
# blue    = '#7e9cd8'
# magenta = '#957fb8'
# cyan    = '#6a9589'
# white   = '#c8c093'
#
# [colors.bright]
# black   = '#727169'
# red     = '#e82424'
# green   = '#98bb6c'
# yellow  = '#e6c384'
# blue    = '#7fb4ca'
# magenta = '#938aa9'
# cyan    = '#7aa89f'
# white   = '#dcd7ba'
#
# [colors.selection]
# background = '#2d4f67'
# foreground = '#c8c093'
#
# [[colors.indexed_colors]]
# index = 16
# color = '#ffa066'
#
# [[colors.indexed_colors]]
# index = 17
# color = '#ff5d62'
# # --------------------------------------------------

# # https://github.com/gabiuz/kape
# # --------------------------------------------------
# [colors.primary]
# background = "#181616"
# foreground = "#d4be98"
#
# [colors.cursor]
# cursor = "#d4be98"
# text = "#181616"
#
# [colors.normal]
# black = "#393737"
# blue = "#7b8fd4"
# cyan = "#689d8a"
# green = "#b4c76e"
# magenta = "#b06880"
# red = "#b53535"
# white = "#c2c2c2"
# yellow = "#e7bb5c"
#
# [colors.bright]
# black = "#4e4a4a"
# blue = "#9aaae0"
# cyan = "#89b8a8"
# green = "#cad98a"
# magenta = "#c8889a"
# red = "#c94040"
# white = "#d4be98"
# yellow = "#f0cc7a"
#
# [colors.search.focused_match]
# background = "#2e2a2a"
# foreground = "#d4be98"
#
# [colors.search.matches]
# background = "#b4c76e"
# foreground = "#c2c2c2"
#
# # url_color = "#7b8fd4"
#
# # orange                #c87941
# # bright_orange         #d4975a
# # --------------------------------------------------

