# exclude files and directories
--glob=!{**/.git/*,**/.cabal/*,**/.cache/*,**/.ghcup/*,**/.gnupg/*,**/.icons/*,**/.local/*,**/.npm/*,**/node_modules/*,**/.password-store/*,**/.ssh/*,**/.stack/*,**/.sessions/*,**/site-packages/*,**/.direnv/*,**/*.age}
# follow symlinks
--follow
# search through hidden files
--hidden

